name:           dbug
author:         anutron
#current:        1.0
category:       Utilities
tags:           [console, debug]
docs:           http://clientcide.com/docs/Core/dbug
demo:           http://www.clientcide.com/wiki/cnet-libraries/01-core/00-dbug